# -*- coding: utf-8 -*-
"""Definiciones de los 3 reels editoriales. Números EXACTOS (math). La voz redondea
en palabras; el visual muestra la cifra exacta (regla del proyecto)."""

REELS = [
    # ============================================================= REEL 1
    {
        "slug": "inflacion_efectivo",
        "edition": "INFORME · INFLACIÓN 2026",
        "source": "INEGI (inflación 3.94%) · Banxico (tasa 7.17%) · ilustrativo, corte 2026",
        "beats": [
            {"id": "b1", "vo": "Tienes cien mil pesos guardados en el banco. Se sienten seguros. Pero cada día, algo invisible los está haciendo más chicos.",
             "scene": {"type": "cover", "kicker": "EL COSTO DE NO DECIDIR",
                        "lines": [{"text": "Dejas"}, {"text": "$100,000"}, {"text": "en efectivo."}],
                        "foot": "Se sienten seguros. Pero algo trabaja en su contra, todos los días."}},
            {"id": "b2", "vo": "Es la inflación. En un año, tus cien mil siguen diciendo cien mil. Pero en lo que de verdad puedes comprar, valen noventa y seis mil doscientos nueve.",
             "scene": {"type": "fallchart", "kicker": "LA INFLACIÓN, EN SILENCIO",
                        "fromLabel": "Hoy compran", "from": 100000, "toLabel": "En un año compran", "to": 96209,
                        "delta": 3791, "axisRight": "−3.94% · 12 MESES",
                        "note": "El efectivo no baja de número: baja de valor."}},
            {"id": "b3", "vo": "Y si en vez de dejarlos quietos los pusieras a trabajar, aunque sea a una tasa modesta, el mismo dinero terminaría en ciento dos mil. La diferencia real: seis mil pesos, solo por decidir.",
             "scene": {"type": "compare", "kicker": "MISMO DINERO, DOS CAMINOS",
                        "left": {"tag": "En efectivo", "value": 96209}, "right": {"tag": "Invertido", "value": 102242},
                        "winner": "right", "note": "A una tasa modesta, el mismo dinero termina en $102,242. La diferencia real: $6,033."}},
            {"id": "b4", "vo": "El efectivo no es gratis: cuesta lo que deja de valer. Guarda esto. Mañana te digo dónde ponerlo para que le gane a la inflación.",
             "scene": {"type": "close", "headline": [{"text": "El efectivo"}, {"text": "no es"}, {"text": "gratis.", "accent": True}],
                        "sub": "Mañana: dónde ponerlo para que le gane a la inflación.", "cta": "Guarda esto"}},
        ],
    },
    # ============================================================= REEL 2
    {
        "slug": "efecto_latte",
        "edition": "INFORME · HÁBITOS 2026",
        "source": "Ilustrativo · $60/día · rendimiento supuesto 8% anual · 20 años",
        "beats": [
            {"id": "b1", "vo": "Un café de sesenta pesos al día. Parece un gasto insignificante. Pero hazle la cuenta a veinte años y no vas a creer el número.",
             "scene": {"type": "cover", "kicker": "UN GASTO INVISIBLE",
                        "lines": [{"text": "Un café"}, {"text": "de $60"}, {"text": "al día."}],
                        "foot": "Parece nada. Hazle la cuenta a veinte años."}},
            {"id": "b2", "vo": "Sesenta pesos al día son veintiún mil novecientos pesos al año. Solo en café.",
             "scene": {"type": "bignum", "label": "Ese café, en un año", "prefix": "$", "value": 21900,
                        "sublabel": "Veintiún mil novecientos pesos al año. Solo en café."}},
            {"id": "b3", "vo": "Si solo lo guardaras, juntarías cuatrocientos treinta y ocho mil. Pero invertido a una tasa del ocho por ciento anual, ese mismo café se convierte en más de un millón de pesos.",
             "scene": {"type": "compare", "kicker": "20 AÑOS DESPUÉS",
                        "left": {"tag": "Solo guardado", "value": 438000}, "right": {"tag": "Invertido al 8%", "value": 1074962},
                        "winner": "right", "note": "El mismo café, invertido, se convierte en más de un millón de pesos."}},
            {"id": "b4", "vo": "Más de un millón de pesos. Ese es el costo real de un café diario: no lo que gastas, sino en lo que se pudo haber convertido.",
             "scene": {"type": "payoff", "kicker": "EL COSTO REAL DE TU CAFÉ", "prefix": "$", "value": 1074962,
                        "deltaText": "en lo que se pudo convertir", "body": "No es el café. Es lo que ese dinero pudo haber sido."}},
            {"id": "b5", "vo": "No te empobrece la compra grande. Te empobrece la pequeña que repites sin pensar. Guarda esto para no olvidarlo.",
             "scene": {"type": "close", "headline": [{"text": "No es el café."}, {"text": "Es el"}, {"text": "hábito.", "accent": True}],
                        "sub": "Los gastos chicos, repetidos, deciden tu futuro.", "cta": "Guarda esto"}},
        ],
    },
    # ============================================================= REEL 3
    {
        "slug": "interes_compuesto",
        "edition": "INFORME · INTERÉS COMPUESTO 2026",
        "source": "Ilustrativo · $2,000/mes · rendimiento supuesto 8% anual",
        "beats": [
            {"id": "b1", "vo": "Dos personas invierten exactamente lo mismo: dos mil pesos al mes. La única diferencia es cuándo empezaron. Y esa diferencia lo cambia todo.",
             "scene": {"type": "cover", "kicker": "LA VENTAJA INJUSTA",
                        "lines": [{"text": "Dos personas."}, {"text": "La misma"}, {"text": "inversión."}],
                        "foot": "Una empezó a los 25. La otra a los 35. La diferencia te va a doler."}},
            {"id": "b2", "vo": "La que empezó a los veinticinco, aportando dos mil al mes, llega a los sesenta y cinco con casi siete millones de pesos.",
             "scene": {"type": "bignum", "label": "Empezó a los 25 — a los 65 tiene", "prefix": "$", "value": 6982016,
                        "sublabel": "Aportó $960,000. Terminó con casi siete millones."}},
            {"id": "b3", "vo": "La que empezó apenas diez años después termina con menos de tres millones. Menos de la mitad.",
             "scene": {"type": "bignum", "label": "Empezó a los 35 — a los 65 tiene", "prefix": "$", "value": 2980719,
                        "accent": True, "sublabel": "Diez años tarde. Menos de la mitad."}},
            {"id": "b4", "vo": "La primera solo aportó doscientos cuarenta mil pesos más. Pero terminó con cuatro millones más. Ese es el poder del interés compuesto.",
             "scene": {"type": "payoff", "kicker": "DIEZ AÑOS DE DIFERENCIA", "prefix": "$", "value": 4001297,
                        "deltaText": "más, por empezar antes", "body": "Aportó solo $240,000 más. Terminó con cuatro millones más. Eso es el interés compuesto."}},
            {"id": "b5", "vo": "El mejor momento para empezar fue hace diez años. El segundo mejor momento es hoy. Guarda esto.",
             "scene": {"type": "close", "headline": [{"text": "El mejor día"}, {"text": "para empezar"}, {"text": "fue ayer.", "accent": True}],
                        "sub": "El segundo mejor es hoy.", "cta": "Guarda esto"}},
        ],
    },
    # ============================================================= REEL 4 — BTC (noticia + logo + i2v)
    {
        "slug": "btc_apuesta",
        "edition": "INFORME · CRIPTO 2026",
        "source": "Fuente: Oficina Nacional de Bitcoin · corte 2 jul 2026",
        "beats": [
            {"id": "b1", "vo": "En dos mil veintiuno, un país pequeño hizo algo que nadie se atrevía: apostar parte de su tesoro nacional al Bitcoin. El mundo entero se rió.",
             "scene": {"type": "cover", "kicker": "BITCOIN · LA APUESTA",
                        "lines": [{"text": "Un país"}, {"text": "apostó al"}, {"text": "Bitcoin.", "accent": True}],
                        "foot": "El mundo se rió en 2021. Hoy la apuesta se ve muy distinta."}},
            {"id": "b2", "vo": "Hoy, El Salvador guarda cerca de siete mil setecientos bitcoins. Una de las reservas soberanas de Bitcoin más grandes del planeta.",
             "scene": {"type": "plate", "kicker": "EL SALVADOR · SU RESERVA", "logo": "logos/bitcoin.svg",
                        "src": "i2v/btc_coin.mp4", "caption": "≈ 7,700 BTC en reserva",
                        "note": "Acumuló cerca de 7,700 bitcoins: una de las mayores reservas soberanas del mundo."}},
            {"id": "b3", "vo": "Los fue acumulando a un precio promedio cercano a los cuarenta y cinco mil dólares. Hoy, cada bitcoin ronda los sesenta y dos mil.",
             "scene": {"type": "compare", "kicker": "COMPRÓ BARATO", "prefix": "$",
                        "left": {"tag": "Compró a", "value": 45000}, "right": {"tag": "Vale hoy", "value": 61900},
                        "winner": "right", "note": "Cada bitcoin vale hoy bastante más de lo que pagó por él."}},
            {"id": "b4", "vo": "Esa reserva vale hoy alrededor de cuatrocientos setenta y siete millones de dólares.",
             "scene": {"type": "bignum", "label": "Su reserva vale hoy", "prefix": "$", "value": 477, "suffix": "M USD",
                        "sublabel": "≈ 7,700 BTC × $61,900, al 2 de julio de 2026."}},
            {"id": "b5", "vo": "Apostaron cuando todos dudaban, y por ahora, esa apuesta va ganando. A veces, el que se atreve, gana. Guarda esto.",
             "scene": {"type": "close", "headline": [{"text": "El que se"}, {"text": "atreve,"}, {"text": "gana.", "accent": True}],
                        "sub": "Al 2 jul 2026 · BTC ≈ $61,900 · Fuente: Oficina Nacional de Bitcoin.", "cta": "Guarda esto"}},
        ],
    },
    # ============================================================= REEL 5 — PETRÓLEO (flagship ultra-creativo, i2v)
    {
        "slug": "petroleo_sube",
        "edition": "INFORME · ENERGÍA 2026",
        "source": "Contenido educativo · el petróleo influye en gasolina e inflación",
        "beats": [
            {"id": "b1", "vo": "El petróleo subió fuerte esta semana. Y eso no se queda en las noticias: baja directo hasta tu bolsillo.",
             "scene": {"type": "hero_i2v", "src": "i2v/oil_barril.mp4", "kicker": "EL PETRÓLEO SUBIÓ",
                        "caption": "Subió fuerte esta semana.", "punch": "Y no se queda en las noticias."}},
            {"id": "b2", "vo": "Primero lo sientes en la bomba: llenar el tanque cuesta más, semana tras semana.",
             "scene": {"type": "hero_i2v", "src": "i2v/oil_surtidor.mp4", "kicker": "PRIMERO, LA GASOLINA",
                        "caption": "Llenar el tanque cuesta más.", "punch": "Semana tras semana."}},
            {"id": "b3", "vo": "Y después, todo lo demás. Sube el transporte, suben los alimentos. Tu dinero se quema más rápido.",
             "scene": {"type": "hero_i2v", "src": "i2v/oil_billete.mp4", "kicker": "DESPUÉS, TODO LO DEMÁS",
                        "caption": "Tu dinero se quema más rápido.", "punch": "Sube el transporte, sube el súper."}},
            {"id": "b4", "vo": "Cuando sube el crudo, lo pagas dos veces: en la bomba y en el súper. Guarda esto.",
             "scene": {"type": "close", "headline": [{"text": "Sube el crudo,"}, {"text": "lo pagas"}, {"text": "dos veces.", "accent": True}],
                        "sub": "En la bomba y en el súper. Mañana: cómo blindar tu gasto.", "cta": "Guarda esto"}},
        ],
    },
]
